# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
deleteBranchAfterMerge: false
reportStatus: true
mergeMethod: squash

minApprovals:
   COLLABORATOR: 1
maxRequestedChanges:
   NONE: 0
blockingLabels:
   - blocked
requiredLabels:
   - merge

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
#rules:
#   - minApprovals:
#        COLLABORATOR: 1
#   - requiredLabels:
#        - merge
