version: 1

merge:
  whitelist:
    labels: ["merge-me"]
  blacklist:
    labels: ["do-not-merge","wip"]
  method: squash
  options:
    squash:
      title: "pull_request_title"
      body: "summarize_commits"
  delete_after_merge: false

update:
  blacklist:
    labels: ["do-not-update"]
  whitelist:
    labels: ["update-me"]
