version: 1

merge:
  whitelist:
    labels: ["merge-me"]
  blacklist:
    labels: ["do-not-merge","wip"]
  method: squash
  options:
    squash:
      title: "pull_request_title"
      body: "empty_body"
  delete_after_merge: true

update:
  blacklist:
    labels: ["do-not-update", "wip"]
  whitelist:
    labels: ["update-me"]
