version: 1

merge:
  whitelist:
    labels: ["merge"]
    comment_substrings: ["==MERGE_WHEN_READY=="]
  blacklist:
    labels: ["do not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: squash
  options:
    squash:
      body: summarize_commits
  delete_after_merge: false

update:
  blacklist:
    labels: ["do-not-update"]